apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig 

metadata:
  name: demo-cluster
  region: us-east-1

nodeGroups:
  - name: demo-ng
    instanceType: t2.small
    desiredCapacity: 3
    minSize: 3
    maxSize: 5
    ssh:
      publicKeyName: eks
cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "controllerManager"]